version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db-data:/data
    env_file:
      - ./.env

  backend:
    image: afivan20/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: afivan20/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - frontend


volumes:
  static_value:
  media_value:
  db-data: